export const pageContainer: string;
export const container: string;
export const toolbar: string;
export const itemGroup: string;
export const itemGroupColumn: string;
export const centerContainer: string;
export const input: string;
export const qrcode: string;
export const url: string;
