export const pageContainer: string;
export const container: string;
export const boxContainer: string;
export const boxRow: string;
export const box: string;
export const redbox: string;
export const greenbox: string;
export const bluebox: string;
export const yellowbox: string;
